# Generated by Django 4.0.8 on 2023-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_category_title_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Battery Health', 'Battery Health'), ('Featured', 'Featured')], default='Like New', max_length=120),
        ),
    ]
