# Generated by Django 4.0.8 on 2023-02-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_name_category_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
    ]
