# Generated by Django 4.0.8 on 2023-02-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Battery Health', 'Battery Health'), ('Featured', 'Featured')], default='Like New', max_length=255),
        ),
    ]
