# Generated by Django 4.0.8 on 2023-02-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_exists',
            field=models.BooleanField(default=True),
        ),
    ]
