# Generated by Django 4.0.8 on 2023-02-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_category_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
